# tekartik analysis_options extension to pedantic
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:tekartik_lints_flutter/strict.yaml

linter:
  rules:
    avoid_print: false