# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:tekartik_lints/strict.yaml

linter:
  rules:
    avoid_print: false