name: sqflite_server_app
description: SQFlite server
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ">=1.0.8"
  sqflite_common_server:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart3a
      path: sqflite_common_server
    version: '>=0.3.2'
  sqflite_porter:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart3a
      path: sqflite_porter
    version: '>=0.2.0'
  tekartik_app_platform:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_platform
    version: '>=0.1.0'
  sqflite_test:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart3a
      path: sqflite_test
    version: '>=0.2.0'
  sqflite: ">=2.4.0"
  sqflite_common_ffi: ">=2.3.4"
  sqflite_common:
  path: ">=1.9.0"
  tekartik_test_menu_flutter:
    git:
      url: https://github.com/tekartik/test_menu_flutter
      ref: dart3a
      path: test_menu_flutter

dev_dependencies:
  process_run: ">=1.2.1+1"
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ">=0.6.1"
  dev_build: ">=1.1.2"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart3a
      path: packages/lints_flutter
    version: '>=0.1.0'

flutter_icons:
  android: true
  ios: true
  image_path: "assets/dev/icon/launcher-icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
resolution: workspace

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
